import { CheckCircle2, CircleX, TriangleAlert, CircleHelp, ExternalLink, RotateCcw, Copy, Check } from 'lucide-react';
import { useState } from 'react';
const cfg = { True: { icon: CheckCircle2, badge: 'border-emerald-400/30 bg-emerald-400/10 text-emerald-300', panel: 'border-emerald-400/20 bg-emerald-400/5', label: 'True' }, False: { icon: CircleX, badge: 'border-rose-400/30 bg-rose-400/10 text-rose-300', panel: 'border-rose-400/20 bg-rose-400/5', label: 'False' }, Misleading: { icon: TriangleAlert, badge: 'border-amber-400/30 bg-amber-400/10 text-amber-300', panel: 'border-amber-400/20 bg-amber-400/5', label: 'Misleading' }, Unverified: { icon: CircleHelp, badge: 'border-slate-400/30 bg-slate-400/10 text-slate-300', panel: 'border-slate-400/20 bg-slate-400/5', label: 'Unverified' } };
export default function VerdictCard({ result, onReset }) {
    const [copied, setCopied] = useState(false); const c = cfg[result.verdict] || cfg.Unverified; const Icon = c.icon;
    const copy = async () => { await navigator.clipboard?.writeText(`SachCheck: ${result.verdict}\n\n${result.explanation}\n\nSources:\n${(result.citedSources || []).join('\n')}`); setCopied(true); setTimeout(() => setCopied(false), 1500) };
    return <div className="mx-auto w-full max-w-3xl animate-fade-up space-y-4">
        <div className={`rounded-[2rem] border p-6 shadow-glow sm:p-8 ${c.panel}`}>
            <div className="flex flex-wrap items-center justify-between gap-4"><div className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-extrabold ${c.badge}`}><Icon size={18} />{c.label}</div><span className="rounded-full border border-slate-700 bg-slate-950/40 px-3 py-1 text-xs text-slate-400">{result.detectedLanguage}</span></div>
            <div className="mt-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-500">Core claim</p><blockquote className="mt-2 border-l-2 border-slate-600 pl-4 text-lg font-medium leading-8 text-slate-100">“{result.extractedClaim}”</blockquote></div>
            <div className="mt-7 rounded-2xl border border-slate-700/60 bg-slate-950/40 p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-300">Why?</p><p className="mt-2 text-[15px] leading-7 text-slate-300">{result.explanation}</p></div>
        </div>
        <div className="glass rounded-[2rem] p-6 sm:p-7"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-500">Evidence</p><h3 className="mt-1 text-lg font-bold">Sources read by SachCheck</h3></div><button onClick={copy} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-3 py-2 text-xs font-semibold text-slate-300 hover:bg-slate-800">{copied ? <Check size={14} /> : <Copy size={14} />} {copied ? 'Copied' : 'Copy report'}</button></div>
            <div className="space-y-2">{(result.citedSources || []).map((url, i) => <a key={url + i} href={url} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-2xl border border-slate-700/60 bg-slate-950/40 px-4 py-3 transition hover:border-teal-400/30 hover:bg-slate-900"><span className="grid h-8 w-8 place-items-center rounded-xl bg-slate-800 text-xs font-bold text-slate-400">{i + 1}</span><span className="min-w-0 flex-1 truncate text-sm text-slate-300">{(() => { try { return new URL(url).hostname.replace('www.', '') } catch { return url } })()}</span><ExternalLink size={15} className="text-slate-500" /></a>)}{!result.citedSources?.length && <p className="text-sm text-slate-500">No source URLs were available for this check.</p>}</div>
        </div><button onClick={onReset} className="mx-auto flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold text-slate-400 hover:text-white"><RotateCcw size={16} /> Check another forward</button>
    </div>
}
